//criar receita
POST http://localhost:3003/recipe
Authorization: token
Content-Type: application/json

{
   "title":"MAÇA DO AMOR ",
   "description":"MAÇA E CARAMELO"
}

###
//busca receita por id do usuario 
GET  http://localhost:3003/recipe/da13b0ac-29fc-46e3-bd22-0508ec9f37e8
Authorization: token
Content-Type: application/json

###
// receitas do usuario que você segue 
GET  http://localhost:3003/user/feed
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE3NzE1MDdiLWJlNTctNGIxNi04NWU0LThkZTIwNTg4MGEzYSIsInJvbGVzIjoiQURNSU4iLCJpYXQiOjE2NjMyNDg1ODEsImV4cCI6MTY2MzMzNDk4MX0.yy0mpdug1QYbbLFcpK24jg0qrFz6WdO_ntvel3HZmo0


###

PUT   http://localhost:3003/recipe/update
Authorization: token
Content-Type: application/json

{
   "id":"0104a97e-246e-4597-a670-c6e08876c351",
   "title":"lasanha",
   "description":"Compra as parada de lasanha e bastante queijo e daleeee"
}

###

DELETE http://localhost:3003/recipe/0104a97e-246e-4597-a670-c6e08876c351
Authorization: token
